### ISSUE TITLE
[ State ] Implement fetch all books from API

### ISSUE THREAD

**Issue by PutraHarianja** [PutraHarianja/Skilvul-Kelompok11-TokoPinter#3]
### Functionality

- [x] Able to fetch books from API asynchronously.
- [x] Able to handle events: **on-loading** event, **on-fulfilled**, and **on-failed**.
- [x] Able to store to state.

### Requirements

- [x] Using React Context as state manager.

### Expected Result

<img width="706" alt="image" src="https://user-images.githubusercontent.com/27900029/141108376-a7403232-0e1a-41de-9ce2-d55f692ee96b.png">

Refs:
- ui: https://www.figma.com/file/K0xIPOP5QmyrfTyAdiCUsL/Toko-Pintar?node-id=0%3A1
- issues: #8

**Comment by josestg** [comment]
DONE!
